public class AfghanCutsceneTankSFX : SFXBank
{
	public SoundFXData TankIdleLoop;

	public SoundFXData TankMoveLoop;

	public SoundFXData TurretRotateLoop;

	public SoundFXData TruckEnter;

	public SoundFXData TankFireTruckExplode;

	public SoundFXData TankOverBlockade;

	public SoundFXData TankPullup;

	public SoundFXData TruckStartUp;

	public SoundFXData VOEnemyPanic;

	public static AfghanCutsceneTankSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanCutsceneTankSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanCutsceneTankSFX>() != null;
		}
	}
}
