public class AfghanS03CutsceneSFX : SFXBank
{
	public SoundFXData S_AFG_DIALOGUE_S03_INTRO01;

	public SoundFXData S_AFG_DIALOGUE_S03_OUTRO01;

	public static AfghanS03CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS03CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS03CutsceneSFX>() != null;
		}
	}
}
