public class AfghanS05CutsceneSFX : SFXBank
{
	public SoundFXData S_AFG_DIALOGUE_S05_CS_INTRO_STRING001;

	public SoundFXData S_AFG_DIALOGUE_S05_CS_OUTRO_STRING002;

	public SoundFXData S_AFG_DIALOGUE_S05_CS_OUTRO_STRING003;

	public SoundFXData S_AFG_DIALOGUE_S05_CS_OUTRO_STRING004;

	public SoundFXData S_AFG_DIALOGUE_S05_CS_OUTRO_STRING005;

	public SoundFXData S_AFG_DIALOGUE_S05_CS_OUTRO_STRING006;

	public static AfghanS05CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS05CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS05CutsceneSFX>() != null;
		}
	}
}
