public class AfghanCutsceneSFX : SFXBank
{
	public SoundFXData Bump;

	public SoundFXData RappelClip;

	public SoundFXData RappelLand;

	public SoundFXData VtolArrive;

	public SoundFXData VtolExtLoop;

	public SoundFXData VtolIntLoop;

	public SoundFXData VtolIntLeave;

	public SoundFXData VtolIntOpen;

	public SoundFXData VtolJetMechTurn;

	public SoundFXData VtolSteadyJetLoop;

	public SoundFXData VtolHitShake;

	public SoundFXData VtolHitShakeLow;

	public SoundFXData AmbientDistantHeliLoop;

	public static AfghanCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanCutsceneSFX>() != null;
		}
	}
}
