public class AfghanS04CutsceneSFX : SFXBank
{
	public SoundFXData S_AFG_DIALOGUE_S04_STRING01;

	public SoundFXData S_AFG_DIALOGUE_S04_STRING02;

	public SoundFXData S_AFG_DIALOGUE_S04_STRING01a;

	public SoundFXData S_AFG_DIALOGUE_S04_STRING86;

	public static AfghanS04CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS04CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS04CutsceneSFX>() != null;
		}
	}
}
