public class AfghanAmbientSFX : SFXBank
{
	public SoundFXData LightBattleLoop;

	public SoundFXData DistantChatter;

	public SoundFXData AAFire;

	public SoundFXData DistantExplosion;

	public SoundFXData HMGBurst;

	public SoundFXData MortarExplosion;

	public SoundFXData GunBattle;

	public SoundFXData BigFireLoop;

	public SoundFXData DistantChatterGMG;

	public static AfghanAmbientSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanAmbientSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanAmbientSFX>() != null;
		}
	}
}
