public class AfghanCutsceneFortGateSFX : SFXBank
{
	public SoundFXData OpenTankHatch;

	public SoundFXData ClimbOntoTank;

	public SoundFXData MountedGunMove;

	public SoundFXData TankSetOff;

	public SoundFXData BlockadeSmash;

	public SoundFXData TankFireShell;

	public SoundFXData GateSmashOpen;

	public SoundFXData TankPullUp;

	public SoundFXData ClimbOutOfTank;

	public SoundFXData GrabKaplan;

	public SoundFXData PistolButt;

	public SoundFXData KaplanBodyfall;

	public SoundFXData KeypadType;

	public SoundFXData TankIdleLoopArFive;

	public SoundFXData TankMoveLoopArFive;

	public SoundFXData TurretRotateArFive;

	public static AfghanCutsceneFortGateSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanCutsceneFortGateSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanCutsceneFortGateSFX>() != null;
		}
	}
}
