public class AfghanS02CSEffectsSFX : SFXBank
{
	public SoundFXData EnemyGunPickup;

	public SoundFXData EnemyGunPoint;

	public SoundFXData AssaultPoint;

	public static AfghanS02CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS02CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS02CSEffectsSFX>() != null;
		}
	}
}
