public class AfghanAmbientHighSFX : SFXBank
{
	public SoundFXData DistantChatter;

	public SoundFXData AAFire;

	public SoundFXData DistantExplosion;

	public SoundFXData HMGBurst;

	public SoundFXData MortarExplosion;

	public SoundFXData DistantChatterGMG;

	public static AfghanAmbientHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanAmbientHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanAmbientHighSFX>() != null;
		}
	}
}
