public class AfghanS02CutsceneSFX : SFXBank
{
	public SoundFXData S_AFG_DIALOGUE_S02_STRING39;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING40;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING41;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING42;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING45;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO02;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03a;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03b;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03c;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03d;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO04;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO05;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO05a;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO06;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO07;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO08;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING39a;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING39b;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING39c;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING40d;

	public static AfghanS02CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS02CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS02CutsceneSFX>() != null;
		}
	}
}
