public class AfghanS02IntroCutsceneSFX : SFXBank
{
	public SoundFXData S_AFG_DIALOGUE_S02_INTRO01;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO02;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO04;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO05;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO06;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO07;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO08;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING02_C;

	public SoundFXData S_AFG_DIALOGUE_S02_STRING06;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03a;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03b;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03c;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO03d;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO05a;

	public static AfghanS02IntroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS02IntroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS02IntroCutsceneSFX>() != null;
		}
	}
}
