public class AfghanCutsceneFollowSFX : SFXBank
{
	public SoundFXData AllyMoveLoop;

	public SoundFXData PlayerMoveLoop;

	public SoundFXData AllyShoot;

	public SoundFXData MoveAgainstWall;

	public SoundFXData AllyKilled;

	public SoundFXData MortarCloseBy;

	public SoundFXData WoodMove;

	public SoundFXData RPGFireTankExplo;

	public SoundFXData TankMoveLoopAfTwoIntro;

	public SoundFXData TankIdleLoopAfTwoIntro;

	public SoundFXData TurretRotateLoopAfTwoIntro;

	public static AfghanCutsceneFollowSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanCutsceneFollowSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanCutsceneFollowSFX>() != null;
		}
	}
}
