public class AfghanS01IntroCutsceneSFX : SFXBank
{
	public SoundFXData S_AFG_INTRO_01;

	public SoundFXData S_AFG_INTRO_01_A;

	public SoundFXData S_AFG_INTRO_02;

	public SoundFXData S_AFG_INTRO_03;

	public SoundFXData S_AFG_INTRO_04;

	public SoundFXData S_AFG_INTRO_05;

	public SoundFXData S_AFG_INTRO_06;

	public SoundFXData S_AFG_INTRO_07;

	public SoundFXData S_AFG_DIALOGUE_S01_OUTRO_01;

	public SoundFXData S_AFG_DIALOGUE_S02_INTRO02;

	public SoundFXData S_PICKUP_AFG_INTRO_TACTICAL_01;

	public static AfghanS01IntroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS01IntroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS01IntroCutsceneSFX>() != null;
		}
	}
}
