public class AfghanS03CSEffectsSFX : SFXBank
{
	public SoundFXData LandDirt;

	public SoundFXData DirtShuffle;

	public SoundFXData JumpUp;

	public SoundFXData HandGrab;

	public SoundFXData PlayerClimbUp;

	public SoundFXData AllyLandDirt;

	public static AfghanS03CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AfghanS03CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AfghanS03CSEffectsSFX>() != null;
		}
	}
}
