public class AmbientCommonSFX : SFXBank
{
	public SoundFXData CarFireLoop;

	public SoundFXData FireGusts;

	public SoundFXData TankerFireLoop;

	public SoundFXData TankerFireGusts;

	public SoundFXData RiverLoop;

	public SoundFXData AmbVTOLGunner;

	public SoundFXData AmbVTOLInterior;

	public SoundFXData DistantIndustrial;

	public SoundFXData SmallGeneratorLoop;

	public SoundFXData BattleChatterWalla;

	public SoundFXData BarrelFireLoop;

	public SoundFXData ElectricSparks;

	public SoundFXData SecurityCamMoveLoop;

	public SoundFXData DistantHeliHindLoop;

	public static AmbientCommonSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<AmbientCommonSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<AmbientCommonSFX>() != null;
		}
	}

	protected override void OnDestroy()
	{
		base.OnDestroy();
	}
}
