public class ArcticCutsceneOutroSFX : SFXBank
{
	public SoundFXData OutroVO1;

	public SoundFXData OutroVO2;

	public SoundFXData OutroVO3;

	public static ArcticCutsceneOutroSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticCutsceneOutroSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticCutsceneOutroSFX>() != null;
		}
	}
}
