public class ArcticAmbientSharedSFX : SFXBank
{
	public SoundFXData WindGustArShared;

	public SoundFXData WindLoopArShared;

	public SoundFXData MainframeAliveLargeLoop;

	public SoundFXData MainframeAliveSmallLoop;

	public SoundFXData MainframeLargeDeadLoop;

	public SoundFXData MainframeSmallDeadLoop;

	public SoundFXData MetalDoorOpen;

	public SoundFXData LargeInteriorLoop;

	public SoundFXData ServerRoomLoop;

	public static ArcticAmbientSharedSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticAmbientSharedSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticAmbientSharedSFX>() != null;
		}
	}
}
