public class ArcticS01MidtroCutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_MIDTRO_01;

	public SoundFXData S_ARC_MIDTRO_02;

	public SoundFXData S_ARC_MIDTRO_03;

	public SoundFXData S_PICKUP_ARC_MIDTRO_TACTICAL_01;

	public SoundFXData S_PICKUP_ARC_MIDTRO_TACTICAL_02;

	public SoundFXData S_PICKUP_ARC_MIDTRO_TACTICAL_03;

	public SoundFXData S_PICKUP_ARC_MIDTRO_TACTICAL_04;

	public SoundFXData S_PICKUP_ARC_MIDTRO_TACTICAL_05;

	public static ArcticS01MidtroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS01MidtroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS01MidtroCutsceneSFX>() != null;
		}
	}
}
