public class ArcticS04CSEffectsSFX : SFXBank
{
	public SoundFXData TruckInArSFour;

	public SoundFXData TruckMoveArSFour;

	public SoundFXData DoorSlamShut;

	public SoundFXData DoorOpen;

	public SoundFXData TruckIdleLoopArSFour;

	public SoundFXData TruckStopArSFour;

	public SoundFXData MantleGrabPitchedDown;

	public SoundFXData FSMetalPitchedDown;

	public SoundFXData MetalDoorOpen;

	public SoundFXData ArcDoorOpenCabin;

	public SoundFXData SnowFSLoop;

	public static ArcticS04CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS04CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS04CSEffectsSFX>() != null;
		}
	}
}
