public class ArcticS07CutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_S07_DIALOGUE_03;

	public SoundFXData S_ARC_S07_DIALOGUE_04;

	public SoundFXData S_ARC_S07_DIALOGUE_05;

	public SoundFXData S_ARC_S07_DIALOGUE_06;

	public SoundFXData S_ARC_S07_DIALOGUE_07;

	public SoundFXData S_ARC_S07_DIALOGUE_08;

	public SoundFXData S_ARC_S07_DIALOGUE_09;

	public SoundFXData S_ARC_S07_DIALOGUE_03a;

	public SoundFXData S_ARC_S07_DIALOGUE_01;

	public SoundFXData S_ARC_S07_DIALOGUE_02;

	public static ArcticS07CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS07CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS07CutsceneSFX>() != null;
		}
	}
}
