public class ArcticCutsceneMidtroSFX : SFXBank
{
	public SoundFXData Empty;

	public static ArcticCutsceneMidtroSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticCutsceneMidtroSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticCutsceneMidtroSFX>() != null;
		}
	}
}
