public class ArcticS07CSEffectsSFX : SFXBank
{
	public SoundFXData ZipTravel;

	public SoundFXData ZipUnhook;

	public SoundFXData AllyLandArSeven;

	public SoundFXData EarthRumbleLoop;

	public SoundFXData MissileLaunchDistant;

	public SoundFXData RocketTailLoop;

	public SoundFXData VtolFlyBy;

	public SoundFXData VtolExtLoopArSeven;

	public SoundFXData VtolJetMechTurnArSeven;

	public SoundFXData VtolSteadyLoopArSeven;

	public SoundFXData VtolDoorOpenArSeven;

	public SoundFXData VtolArriveLand;

	public SoundFXData EnemyFireloop;

	public SoundFXData BulletImpsRics;

	public SoundFXData PlayerClimbUpArSeven;

	public SoundFXData DiveGrab;

	public SoundFXData VtolTakeOffOne;

	public SoundFXData VtolTakeOffTwo;

	public SoundFXData AllyKilled;

	public SoundFXData MissileIncoming;

	public SoundFXData VtolDoorClose;

	public SoundFXData OutroEnding;

	public SoundFXData ArcOutroMusic;

	public static ArcticS07CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS07CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS07CSEffectsSFX>() != null;
		}
	}
}
