public class ArcticS04CutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_S04_DIALOGUE_01;

	public SoundFXData S_ARC_S04_DIALOGUE_03;

	public SoundFXData S_ARC_S04_DIALOGUE_04;

	public SoundFXData S_ARC_S04_DIALOGUE_05;

	public SoundFXData S_ARC_S04_DIALOGUE_06;

	public SoundFXData S_ARC_S04_DIALOGUE_07;

	public SoundFXData S_ARC_S04_DIALOGUE_08;

	public SoundFXData S_ARC_S04_DIALOGUE_14;

	public SoundFXData S_ARC_S04_DIALOGUE_01a;

	public SoundFXData S_ARC_S04_DIALOGUE_01b;

	public SoundFXData S_ARC_S04_DIALOGUE_02b;

	public SoundFXData S_ARC_S04_DIALOGUE_06a;

	public SoundFXData S_ARC_S04_DIALOGUE_06b;

	public static ArcticS04CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS04CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS04CutsceneSFX>() != null;
		}
	}
}
