public class ArcticS04CSEffectsHighSFX : SFXBank
{
	public SoundFXData FSMetalPitchedDown;

	public static ArcticS04CSEffectsHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS04CSEffectsHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS04CSEffectsHighSFX>() != null;
		}
	}
}
