public class ArcticS02CSEffectsSFX : SFXBank
{
	public SoundFXData SniperDial;

	public SoundFXData KnifeDraw;

	public SoundFXData StabHand;

	public SoundFXData FacePunch;

	public SoundFXData BodyGrab;

	public SoundFXData ThrowIntoComputer;

	public SoundFXData HandOnShoulder;

	public SoundFXData PatDownBody;

	public SoundFXData RemovePaper;

	public SoundFXData RemoveKnife;

	public SoundFXData MetalDoorOpen;

	public SoundFXData InternalExplosion;

	public SoundFXData FSSnowLoop;

	public static ArcticS02CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS02CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS02CSEffectsSFX>() != null;
		}
	}
}
