public class ArcticCutsceneSFX : SFXBank
{
	public SoundFXData BoatIdle;

	public SoundFXData BoatEngineOff;

	public SoundFXData BoatRunFast;

	public SoundFXData BoatRunSlow;

	public SoundFXData BoatRunSplashLoop;

	public SoundFXData OceanWind;

	public SoundFXData GrabClimbOntoPier;

	public SoundFXData StandUpOnPier;

	public SoundFXData TruckArriveArSOne;

	public SoundFXData TruckStopArSOne;

	public SoundFXData DroneCSTouchBeepFirst;

	public SoundFXData DroneCSTouchBeepSecond;

	public SoundFXData DroneCSTouchBeepComplete;

	public SoundFXData IntroVO1;

	public SoundFXData IntroVO2;

	public SoundFXData IntroVO3;

	public SoundFXData IntroVO4;

	public SoundFXData S_ARC_S01_DIALOGUE_01;

	public SoundFXData SnowFootstepsLoop;

	public SoundFXData HeliEngineLoopClose;

	public static ArcticCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticCutsceneSFX>() != null;
		}
	}
}
