public class ArcticS07CSEffectsHighSFX : SFXBank
{
	public SoundFXData BulletImpsRics;

	public static ArcticS07CSEffectsHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS07CSEffectsHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS07CSEffectsHighSFX>() != null;
		}
	}
}
