public class ArcticCutsceneGateSFX : SFXBank
{
	public SoundFXData KeypadType;

	public SoundFXData KeypadUnlock;

	public SoundFXData GateOpen;

	public SoundFXData GateClose;

	public SoundFXData HandKeypad;

	public SoundFXData KeypadDestroy;

	public SoundFXData SnowFootsteps;

	public SoundFXData HandOnSandbag;

	public SoundFXData HandsOnGun;

	public SoundFXData GunTiltUp;

	public SoundFXData MidtroVO1;

	public SoundFXData MidtroVO2;

	public SoundFXData MidtroVO3;

	public static ArcticCutsceneGateSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticCutsceneGateSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticCutsceneGateSFX>() != null;
		}
	}
}
