public class ArcticS03IntroCutsceneSFX : SFXBank
{
	public SoundFXData A_ARC_S03_DIALOGUE_01;

	public static ArcticS03IntroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS03IntroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS03IntroCutsceneSFX>() != null;
		}
	}
}
