public class ArcticS06CSEffectsSFX : SFXBank
{
	public SoundFXData TruckMoveArSix;

	public SoundFXData TruckStopArSix;

	public SoundFXData TruckIdle;

	public SoundFXData DoorCloseArSix;

	public SoundFXData DoorSlamShutArSix;

	public SoundFXData TruckEngineOff;

	public SoundFXData TruckDoorOpen;

	public SoundFXData TruckDoorClose;

	public SoundFXData FSStoneLoopSlowArSix;

	public SoundFXData DoorGrab;

	public SoundFXData DoorMovement;

	public SoundFXData DoorOpen;

	public SoundFXData BinLidDoorClose;

	public SoundFXData ZiplineHookOn;

	public SoundFXData ZiplineTravel;

	public SoundFXData ZiplineUnhook;

	public SoundFXData MissileLaunch;

	public SoundFXData FSMetalLoopFastArSix;

	public SoundFXData BigButtonPress;

	public static ArcticS06CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS06CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS06CSEffectsSFX>() != null;
		}
	}
}
