public class ArcticS03CSEffectsSFX : SFXBank
{
	public SoundFXData HandGrabMetal;

	public SoundFXData WpnMovementSmall;

	public SoundFXData HeliFlyBy;

	public SoundFXData HeliLoop;

	public SoundFXData HeliLoopLowerPitch;

	public SoundFXData HeliWindDown;

	public SoundFXData FSSnowLoopArThree;

	public static ArcticS03CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS03CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS03CSEffectsSFX>() != null;
		}
	}
}
