public class ArcticS03MidtroCutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_S3_MIDTRO_01;

	public SoundFXData S_ARC_S3_MIDTRO_02;

	public SoundFXData S_PICKUP_ARC_S3_MIDTRO_03;

	public SoundFXData S_ARC_S3_MIDTRO_04;

	public SoundFXData S_ARC_S3_MIDTRO_05;

	public static ArcticS03MidtroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS03MidtroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS03MidtroCutsceneSFX>() != null;
		}
	}
}
