public class ArcticAmbientHighSFX : SFXBank
{
	public SoundFXData BuildingRattle;

	public SoundFXData MetalShipStress;

	public SoundFXData WindGust;

	public SoundFXData WoodenPierStress;

	public SoundFXData CraneRattle;

	public SoundFXData PoleRattle;

	public SoundFXData Tannoy;

	public SoundFXData MuffedChat;

	public static ArcticAmbientHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticAmbientHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticAmbientHighSFX>() != null;
		}
	}
}
