public class ArcticS6AmbientSFX : SFXBank
{
	public SoundFXData UndergroundFullLoop;

	public SoundFXData VentMachineLoop;

	public static ArcticS6AmbientSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS6AmbientSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS6AmbientSFX>() != null;
		}
	}
}
