public class ArcticS06CutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_S06_DIALOGUE_01;

	public SoundFXData S_ARC_S06_DIALOGUE_01b;

	public SoundFXData S_ARC_S06_DIALOGUE_01c;

	public SoundFXData S_ARC_S06_DIALOGUE_57;

	public SoundFXData S_ARC_S06_DIALOGUE_58;

	public SoundFXData S_ARC_S06_DIALOGUE_59;

	public static ArcticS06CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS06CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS06CutsceneSFX>() != null;
		}
	}
}
