public class ArcticS03OutroCutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_S3_OUTRO_01;

	public SoundFXData S_ARC_S3_OUTRO_02;

	public SoundFXData S_ARC_S3_OUTRO_03;

	public static ArcticS03OutroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS03OutroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS03OutroCutsceneSFX>() != null;
		}
	}
}
