public class ArcticS01IntroCutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_INTRO_01;

	public SoundFXData S_ARC_INTRO_02;

	public SoundFXData S_ARC_INTRO_03;

	public SoundFXData S_ARC_INTRO_04;

	public static ArcticS01IntroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS01IntroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS01IntroCutsceneSFX>() != null;
		}
	}
}
