public class ArcticS01OutroCutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_OUTRO_01;

	public SoundFXData S_ARC_OUTRO_02;

	public SoundFXData S_ARC_OUTRO_03;

	public static ArcticS01OutroCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS01OutroCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS01OutroCutsceneSFX>() != null;
		}
	}
}
