public class ArcticS02CSEffectsHighSFX : SFXBank
{
	public SoundFXData SniperDial;

	public SoundFXData PatDownBody;

	public static ArcticS02CSEffectsHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS02CSEffectsHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS02CSEffectsHighSFX>() != null;
		}
	}
}
