public class ArcticS01BriefingCutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_BRIEFING_01;

	public SoundFXData S_ARC_BRIEFING_01b;

	public SoundFXData S_ARC_BRIEFING_02;

	public SoundFXData S_ARC_BRIEFING_03;

	public SoundFXData S_ARC_BRIEFING_04;

	public SoundFXData S_ARC_BRIEFING_04b;

	public SoundFXData S_ARC_BRIEFING_05;

	public SoundFXData S_ARC_BRIEFING_05b;

	public SoundFXData S_ARC_BRIEFING_06;

	public static ArcticS01BriefingCutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS01BriefingCutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS01BriefingCutsceneSFX>() != null;
		}
	}
}
