public class ArcticS05CutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_S05_DIALOGUE_01;

	public static ArcticS05CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS05CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS05CutsceneSFX>() != null;
		}
	}
}
