public class ArcticS02CutsceneSFX : SFXBank
{
	public SoundFXData S_ARC_S02_DIALOGUE_01A;

	public SoundFXData S_PICKUP_ARC_S02_DIALOGUE_01B;

	public SoundFXData S_PICKUP_ARC_S02_DIALOGUE_01C;

	public SoundFXData S_PICKUP_ARC_S02_DIALOGUE_01D;

	public SoundFXData S_ARC_S02_DIALOGUE_01E;

	public SoundFXData S_ARC_S02_DIALOGUE_33A;

	public SoundFXData S_ARC_S02_DIALOGUE_33B;

	public SoundFXData S_ARC_S02_DIALOGUE_33C;

	public SoundFXData S_ARC_S02_DIALOGUE_33D;

	public SoundFXData S_ARC_S02_DIALOGUE_33E;

	public SoundFXData S_ARC_S02_DIALOGUE_33F;

	public SoundFXData S_ARC_S02_DIALOGUE_34A;

	public SoundFXData S_ARC_S02_DIALOGUE_34B;

	public SoundFXData S_ARC_S02_DIALOGUE_34C;

	public SoundFXData S_ARC_S02_DIALOGUE_34D;

	public SoundFXData S_ARC_S02_DIALOGUE_16;

	public static ArcticS02CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ArcticS02CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ArcticS02CutsceneSFX>() != null;
		}
	}
}
