public class BoatIntroSFX : SFXBank
{
	public SoundFXData Shot1;

	public SoundFXData Shot2;

	public SoundFXData Shot3;

	public static BoatIntroSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<BoatIntroSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<BoatIntroSFX>() != null;
		}
	}
}
