public class BodyFallSFX : SFXBank
{
	public SoundFXData BodyFallWood;

	public SoundFXData BodyFallWater;

	public SoundFXData BodyFallDirt;

	public SoundFXData BodyFallMetalSolid;

	public SoundFXData BodyFallStone;

	public SoundFXData BodyFallSnow;

	public SoundFXData BodyFallGeneric;

	public SoundFXData BodyFallStealth;

	public static BodyFallSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<BodyFallSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<BodyFallSFX>() != null;
		}
	}
}
