public class BodyFallHighSFX : SFXBank
{
	public SoundFXData BodyFallWood;

	public SoundFXData BodyFallWater;

	public SoundFXData BodyFallDirt;

	public SoundFXData BodyFallMetalSolid;

	public SoundFXData BodyFallStone;

	public SoundFXData BodyFallSnow;

	public SoundFXData BodyFallGeneric;

	public SoundFXData BodyFallStealth;

	public static BodyFallHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<BodyFallHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<BodyFallHighSFX>() != null;
		}
	}
}
