public class CarrierAmbientHighSFX : SFXBank
{
	public SoundFXData ExteriorLoop;

	public SoundFXData ExteriorAlarmLoop;

	public SoundFXData InteriorLoop;

	public SoundFXData InteriorAlarmLoop;

	public SoundFXData RandomOneshotA;

	public SoundFXData RandomOneshotB;

	public SoundFXData SmokeLoop;

	public SoundFXData ComputerLoop;

	public SoundFXData ComputerLoopLarge;

	public SoundFXData MachineLoop;

	public SoundFXData BrokenMachineLoop;

	public SoundFXData RainLoop;

	public static CarrierAmbientHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<CarrierAmbientHighSFX>();
		}
	}
}
