public class CharacterSFX : SFXBank
{
	public SoundFXData DamageHealthMedium;

	public SoundFXData DamageHealthMediumLoop;

	public SoundFXData DamageHealthLow;

	public SoundFXData DamageHealthLowEnd;

	public SoundFXData PlayerDeath;

	public SoundFXData PlayerDeathLastMan;

	public SoundFXData HoldBreathStart;

	public SoundFXData HoldBreathLoop;

	public SoundFXData HoldBreathEnd;

	public SoundFXData HoldBreathEndForced;

	public SoundFXData IntelCollectedVO;

	public SoundFXData HitBySniper;

	public static CharacterSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<CharacterSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<CharacterSFX>() != null;
		}
	}
}
