public class DominationVOSFX : SFXBank
{
	public SoundFXData S_DOMINATION_DIALOGUE_POINTALOST_VAR1;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTALOST_VAR2;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTALOST_VAR3;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTBLOST_VAR1;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTBLOST_VAR2;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTBLOST_VAR3;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTCLOST_VAR1;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTCLOST_VAR2;

	public SoundFXData S_DOMINATION_DIALOGUE_POINTCLOST_VAR3;

	public SoundFXData S_DOMINATION_DIALOGUE_ALLPOINTSWON;

	public SoundFXData S_DOMINATION_DIALOGUE_ALLPOINTSLOST_VAR1;

	public SoundFXData S_DOMINATION_DIALOGUE_ALLPOINTSLOST_VAR2;

	public SoundFXData S_DOMINATION_DIALOGUE_ALLPOINTSLOST_VAR3;

	public SoundFXData S_DOMINATION_DIALOGUE_TIMERUNNINGOUT;

	public SoundFXData S_TT_DIALOGUE_TIMERUNNINGOUT_VAR1;

	public SoundFXData S_TT_DIALOGUE_TIMERUNNINGOUT_VAR2;

	public SoundFXData S_TT_DIALOGUE_TIMERUNNINGOUT_VAR3;

	public SoundFXData S_TT_DIALOGUE_TIMEOUT;

	public static DominationVOSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<DominationVOSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<DominationVOSFX>() != null;
		}
	}
}
