public class EnvironmentSFX : SFXBank
{
	public SoundFXData SlidingGate;

	public SoundFXData RainOnMetalRoof;

	public SoundFXData AirConUnit;

	public SoundFXData LightBuzz;

	public SoundFXData AirConVent;

	public SoundFXData PoleRattle;

	public SoundFXData SteamVent;

	public SoundFXData WaterDrip;

	public SoundFXData ComputerHack;

	public SoundFXData AlarmSiren1;

	public SoundFXData AlarmSiren2;

	public SoundFXData AlarmSiren3;

	public SoundFXData AlarmSiren4;

	public static EnvironmentSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<EnvironmentSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<EnvironmentSFX>() != null;
		}
	}
}
