public class ExplosivesHighSFX : SFXBank
{
	public SoundFXData GrenadeBounce;

	public SoundFXData GrenadeExplosion;

	public SoundFXData BarrelExplode;

	public SoundFXData CarExplode;

	public static ExplosivesHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ExplosivesHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ExplosivesHighSFX>() != null;
		}
	}
}
