public class ExplosivesSFX : SFXBank
{
	public SoundFXData GrenadeRelease;

	public SoundFXData GrenadeBounce;

	public SoundFXData GrenadeBounceSoft;

	public SoundFXData GrenadeBounceWater;

	public SoundFXData GrenadeExplosion;

	public SoundFXData GrenadeExplodeUnderwater;

	public SoundFXData C4DoorBombPlant;

	public SoundFXData C4DoorFuseClick;

	public SoundFXData C4DoorFuseBeep;

	public SoundFXData C4DoorBreachExplosion;

	public SoundFXData ExplodeMortar;

	public SoundFXData BarrelExplode;

	public SoundFXData CarExplode;

	public SoundFXData AmmoCrateDestroy;

	public SoundFXData ClaymorePlant;

	public SoundFXData ClaymoreTriggered;

	public SoundFXData HelicopterExplode;

	public static ExplosivesSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ExplosivesSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ExplosivesSFX>() != null;
		}
	}
}
