public class FoleyHighSFX : SFXBank
{
	public SoundFXData PlayerCrouch;

	public SoundFXData PlayerStand;

	public static FoleyHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<FoleyHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<FoleyHighSFX>() != null;
		}
	}
}
