public class FoleySFX : SFXBank
{
	public SoundFXData FoleyClimbUp;

	public SoundFXData FoleyDropDown;

	public SoundFXData FoleyGrab;

	public SoundFXData FoleyMovementFast;

	public SoundFXData FoleyMovementSlow;

	public SoundFXData PlayerCrouch;

	public SoundFXData PlayerStand;

	public static FoleySFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<FoleySFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<FoleySFX>() != null;
		}
	}
}
