using UnityEngine;

public class FontManager : SingletonMonoBehaviour
{
	public Material[] FontMaterials;

	public Texture[] x2Texture;

	public TextAsset[] x2FontDef;

	public static FontManager Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<FontManager>();
		}
	}

	protected override void Awake()
	{
		base.Awake();
		if (TBFUtils.IsRetinaHdDevice())
		{
			Debug.Log("I'm a retina HD device");
			for (int i = 0; i < FontMaterials.Length; i++)
			{
				Debug.Log("Unloading :" + FontMaterials[i].mainTexture.name);
				Resources.UnloadAsset(FontMaterials[i].mainTexture);
				FontMaterials[i].mainTexture = x2Texture[i];
			}
			FontStore.PopulateHiResFonts(x2FontDef);
		}
		else
		{
			Debug.Log("I'm not retina HD device");
			for (int j = 0; j < x2Texture.Length; j++)
			{
				Debug.Log("Unloading :" + x2Texture[j].name);
				Resources.UnloadAsset(x2Texture[j]);
				x2Texture[j] = null;
			}
		}
	}
}
