public class FootstepsSFX : SFXBank
{
	public SoundFXData FSWalkWood;

	public SoundFXData FSWalkSnow;

	public SoundFXData FSRunWood;

	public SoundFXData FSRunSnow;

	public SoundFXData FSRunMetal;

	public SoundFXData FSRunMasonry;

	public SoundFXData FSRunIce;

	public SoundFXData FSRunWater;

	public SoundFXData FSRunCarpet;

	public SoundFXData FSRunDirt;

	public SoundFXData FSRunGlass;

	public SoundFXData FSRunGrass;

	public SoundFXData FSRunLeaves;

	public SoundFXData FSRunMud;

	public SoundFXData FSRunCement;

	public SoundFXData FSRunSand;

	public SoundFXData LandWood;

	public SoundFXData LandDirt;

	public SoundFXData LandMetalSolid;

	public SoundFXData LandStone;

	public SoundFXData LandSnow;

	public static FootstepsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<FootstepsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<FootstepsSFX>() != null;
		}
	}
}
