using UnityEngine;

public class GameDialogueSFX : SFXBank
{
	public DialogueSFXData DialogueData;

	public static GameDialogueSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<GameDialogueSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<GameDialogueSFX>() != null;
		}
	}

	protected override void OnDestroy()
	{
		if (Application.isPlaying && SoundManager.Instance.HasGamePlayStarted())
		{
			base.OnDestroy();
			DialogueData = null;
		}
	}

	public float PlayDialogue(MissionListings.eMissionID missionId, int dialogueId)
	{
		float result = 0f;
		if (DialogueData.Dialogue != null && dialogueId >= 0 && dialogueId < DialogueData.Dialogue.Length)
		{
			SoundManager.SoundInstance soundInstance = DialogueData.Dialogue[dialogueId].Play2D();
			result = soundInstance.SampleLength;
		}
		return result;
	}

	public void StopAllDialogue(MissionListings.eMissionID missionId)
	{
		if (DialogueData.Dialogue != null)
		{
			for (int i = 0; i < DialogueData.Dialogue.Length; i++)
			{
				DialogueData.Dialogue[i].Stop2D();
			}
		}
	}

	public bool SearchForIds(string text, out int dialogueId, out int firstRepeatDialogueId, out int subsequentRepeatDialogueId)
	{
		bool flag = false;
		dialogueId = -1;
		firstRepeatDialogueId = -1;
		subsequentRepeatDialogueId = -1;
		if (text.StartsWith("S_"))
		{
			text = text.Substring(2, text.Length - 2);
			text = "A_" + text;
		}
		if (DialogueData.Dialogue != null)
		{
			for (int i = 0; i < DialogueData.Dialogue.Length; i++)
			{
				if (flag)
				{
					break;
				}
				if (DialogueData.Dialogue[i].m_audioSourceData[0] != null)
				{
					string strippedName = GetStrippedName(DialogueData.Dialogue[i].m_audioSourceData[0].name);
					string strippedName2 = GetStrippedName(text);
					if (strippedName == strippedName2)
					{
						string text2 = DialogueData.Dialogue[i].m_audioSourceData[0].name.ToUpper();
						if (text2.Contains("FIRSTREPEAT"))
						{
							firstRepeatDialogueId = i;
						}
						else if (text2.Contains("SUBSEQUENTREPEAT"))
						{
							subsequentRepeatDialogueId = i;
						}
						else
						{
							dialogueId = i;
						}
					}
				}
				if (dialogueId != -1 && firstRepeatDialogueId != -1 && subsequentRepeatDialogueId != -1)
				{
					flag = true;
				}
			}
		}
		return flag;
	}

	private string GetStrippedName(string text)
	{
		string text2 = text.ToUpper();
		string text3 = text2;
		if (text3.EndsWith("_FIRSTREPEAT"))
		{
			int length = text3.LastIndexOf("_FIRSTREPEAT");
			text2 = text2.Substring(0, length);
		}
		else if (text3.EndsWith("_SUBSEQUENTREPEAT"))
		{
			int length2 = text3.LastIndexOf("_SUBSEQUENTREPEAT");
			text2 = text2.Substring(0, length2);
		}
		return text2;
	}
}
