public class GeneralSettings : SingletonMonoBehaviour
{
	private const string HasRatedAppKey = "HasRatedApp";

	private const string HasKInvitedKey = "HasKInvited";

	public static GeneralSettings Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<GeneralSettings>();
		}
	}

	public bool HasRatedApp
	{
		get
		{
			return SecureStorage.Instance.GetBool("HasRatedApp");
		}
		set
		{
			SecureStorage.Instance.SetBool("HasRatedApp", value);
		}
	}

	public bool HasKInvited
	{
		get
		{
			return SecureStorage.Instance.GetBool("HasKInvited");
		}
		set
		{
			SecureStorage.Instance.SetBool("HasKInvited", value);
		}
	}
}
