public class GlobeSFX : SFXBank
{
	public SoundFXData ZoomIn;

	public SoundFXData ZoomInWithC;

	public SoundFXData ZoomOut;

	public SoundFXData ZoomOutWithB;

	public SoundFXData GlobeStart;

	public SoundFXData GlobeSpin;

	public SoundFXData GlobeMarkerLoop;

	public SoundFXData TextType;

	public static GlobeSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<GlobeSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<GlobeSFX>() != null;
		}
	}
}
