public class GMGSFX : SFXBank
{
	public SoundFXData WaveComplete;

	public SoundFXData NextWave;

	public SoundFXData AmmoCacheAvailable;

	public SoundFXData AmmoCacheUsed;

	public SoundFXData NextWaveCountdown;

	public SoundFXData NextWaveCountdownLast;

	public SoundFXData TokenAwarded;

	public SoundFXData MysteryCacheAvailable;

	public SoundFXData MysteryCacheUsed;

	public SoundFXData MysteryReward;

	public SoundFXData MysteryBoxOpen;

	public SoundFXData MysteryBoxClose;

	public SoundFXData SonicBombVar1;

	public SoundFXData SonicBombVar2;

	public SoundFXData SonicBombVar3;

	public SoundFXData InvincibilityActivate;

	public SoundFXData InvincibilityDeactivate;

	public SoundFXData SpeedBoostActivate;

	public SoundFXData SpeedBoostDeactivate;

	public SoundFXData XPBonusActivate;

	public SoundFXData XPBonusDeactivate;

	public SoundFXData XPBonus;

	public SoundFXData TimeFreezeActivate;

	public SoundFXData TimeFreezeDeactivate;

	public SoundFXData TimedRewardExpiring;

	public SoundFXData ObjectiveCaptureStart;

	public SoundFXData ObjectiveCaptureLoop;

	public SoundFXData ObjectiveSecure;

	public SoundFXData ObjectiveAmbientSound;

	public static GMGSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<GMGSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<GMGSFX>() != null;
		}
	}
}
