public class ImpactSFX : SFXBank
{
	public SoundFXData BulletHitGlass;

	public SoundFXData BulletHitCarpet;

	public SoundFXData BulletHitWood;

	public SoundFXData BulletHitWater;

	public SoundFXData BulletHitDirt;

	public SoundFXData BulletHitBody;

	public SoundFXData BulletHitFoliage;

	public SoundFXData BulletHitMasonry;

	public SoundFXData BulletHitMetal;

	public SoundFXData BulletHitSnow;

	public SoundFXData BulletHitIce;

	public SoundFXData BulletHitRock;

	public SoundFXData BulletHitDuct;

	public SoundFXData BulletHitSand;

	public SoundFXData HeadshotKill;

	public SoundFXData BulletRicochetGlass;

	public SoundFXData BulletRicochetCarpet;

	public SoundFXData BulletRicochetWood;

	public SoundFXData BulletRicochetWater;

	public SoundFXData BulletRicochetDirt;

	public SoundFXData BulletRicochetMasonry;

	public SoundFXData BulletRicochetMetal;

	public SoundFXData BulletRicochetSnow;

	public SoundFXData BulletRicochetIce;

	public SoundFXData BulletRicochetRock;

	public SoundFXData BulletRicochetDuct;

	public SoundFXData BulletRicochetSand;

	public SoundFXData MetalCastingWood;

	public SoundFXData MetalCastingWater;

	public SoundFXData MetalCastingDirt;

	public SoundFXData MetalCastingStone;

	public SoundFXData MetalCastingMetal;

	public SoundFXData MetalCastingSnow;

	public SoundFXData DeadBodyHitGround;

	public SoundFXData GlassShatterBig;

	public SoundFXData MonitorScreenSmash;

	public SoundFXData GarbageBagDestroy;

	public static ImpactSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ImpactSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ImpactSFX>() != null;
		}
	}
}
