public class InterfaceSFX : SFXBank
{
	public SoundFXData ContextMenuOn;

	public SoundFXData ContextMenuRollover;

	public SoundFXData ContextMenuSelect;

	public SoundFXData ContextMenuCancel;

	public SoundFXData GeneralButtonPress;

	public SoundFXData MessageBoxOn;

	public SoundFXData TextType;

	public SoundFXData HUDActionInfoBox;

	public SoundFXData HUDSelectAction;

	public SoundFXData ViewChange;

	public SoundFXData SelectUnit;

	public SoundFXData PlaceUnit;

	public SoundFXData SlowmoStart;

	public SoundFXData SlowmoLoopBreath;

	public SoundFXData SlowmoLoopTin;

	public SoundFXData SlowmoEnd;

	public SoundFXData ViewChangeStatic;

	public SoundFXData TargetSnap;

	public SoundFXData TargetSnapUnavailable;

	public SoundFXData ObjectiveShowHighlightBlip;

	public SoundFXData UIScrollTick;

	public SoundFXData MedPackHeal;

	public SoundFXData WeaponSwitch;

	public SoundFXData SwitchUnitFPP;

	public SoundFXData PickupIntel;

	public SoundFXData TPPDroneLoop;

	public SoundFXData ObjectiveFail;

	public static InterfaceSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<InterfaceSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<InterfaceSFX>() != null;
		}
	}
}
