public class KowloonS02CSEffectsSFX : SFXBank
{
	public SoundFXData FSMetalLoopFastKoTwo;

	public SoundFXData FSMetalLoopFast50cKoTwo;

	public SoundFXData LandKoTwo;

	public SoundFXData ExplosionKoTwoMidtro;

	public SoundFXData MasonryDebrisKoTwo;

	public SoundFXData UntieHands;

	public SoundFXData FSStoneLoopSlowKoTwo;

	public static KowloonS02CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowloonS02CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowloonS02CSEffectsSFX>() != null;
		}
	}
}
