public class KowloonAmbientSFX : SFXBank
{
	public SoundFXData CityLoop;

	public SoundFXData RainWindLoop;

	public SoundFXData RoofRainLoopLarge;

	public SoundFXData RoofRainLoopSmall;

	public SoundFXData EerieWindLoop;

	public SoundFXData DogBarks;

	public static KowloonAmbientSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowloonAmbientSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowloonAmbientSFX>() != null;
		}
	}
}
