public class KowloonS03CSEffectsSFX : SFXBank
{
	public SoundFXData VtolTakeOffKoThree;

	public SoundFXData VtolExtLoopKoThree;

	public SoundFXData VtolIntLoopKoThree;

	public SoundFXData VtolSteadyLoopKoThree;

	public SoundFXData DoorJammed;

	public SoundFXData VtolSideDoorOpen;

	public SoundFXData MissileIncomingLoopKoThree;

	public SoundFXData RPGWhizByKoThree;

	public SoundFXData VtolHitMissile;

	public SoundFXData VtolHitKoThree;

	public SoundFXData VtolDamagedLoopKoThree;

	public SoundFXData InteriorBumpKoThree;

	public SoundFXData GunDrop;

	public SoundFXData VtolJetMechTurnKoThree;

	public SoundFXData VtolDown;

	public SoundFXData VtolCrashKoThree;

	public SoundFXData ZiplineHookOnKoThree;

	public SoundFXData ZiplineTravelKoThree;

	public static KowloonS03CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowloonS03CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowloonS03CSEffectsSFX>() != null;
		}
	}
}
