public class KowloonAmbientHighSFX : SFXBank
{
	public SoundFXData DogBarks;

	public static KowloonAmbientHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowloonAmbientHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowloonAmbientHighSFX>() != null;
		}
	}
}
