public class KowloonS04CSEffectsSFX : SFXBank
{
	public SoundFXData ZiplineShort;

	public SoundFXData ZiplineUnhookKoFour;

	public SoundFXData ExplosionKoFour;

	public SoundFXData DoorBarge;

	public SoundFXData DoorPush;

	public SoundFXData DoorKickOpen;

	public SoundFXData DoorSlamShut;

	public SoundFXData DoorExplode;

	public static KowloonS04CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowloonS04CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowloonS04CSEffectsSFX>() != null;
		}
	}
}
