public class KowloonS01CSEffectsSFX : SFXBank
{
	public SoundFXData VtolIntLoop;

	public SoundFXData VtolDamagedLoop;

	public SoundFXData VtolCrash;

	public SoundFXData AAFire;

	public SoundFXData VtolHit;

	public SoundFXData DoorOpenWind;

	public SoundFXData WingsuitFlightLoop;

	public SoundFXData AllyWingsuitDrop;

	public SoundFXData ParachuteOpen;

	public SoundFXData ParachuteLoop;

	public SoundFXData ParachuteLand;

	public SoundFXData StealthBodyGrab;

	public SoundFXData ClimbUpKoOne;

	public SoundFXData FSMetalLoopFastKoOne;

	public SoundFXData ZiplineHookOnKoOne;

	public SoundFXData ZiplineTravelLong;

	public SoundFXData ZiplineUnhookKoOne;

	public SoundFXData SniperShot;

	public SoundFXData KneckCrack;

	public static KowloonS01CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowloonS01CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowloonS01CSEffectsSFX>() != null;
		}
	}
}
