public class KowloonS05CSEffectsSFX : SFXBank
{
	public SoundFXData AllyOneStand;

	public SoundFXData AllyTwoStand;

	public SoundFXData PlayerStandOne;

	public SoundFXData PlayerStandTwo;

	public SoundFXData KwlnOutroFullBakeSFX;

	public SoundFXData MinigunFireLoopKoFive;

	public SoundFXData MinigunFireLoop60cUpKoFive;

	public SoundFXData BulletImpacts;

	public SoundFXData BurningFireLoop;

	public SoundFXData RunJumpDown;

	public SoundFXData HeliImpacts;

	public SoundFXData HeliDown;

	public SoundFXData HeliWreckVtolDoor;

	public SoundFXData VtolLiftOff;

	public SoundFXData VtolDoorClose;

	public SoundFXData FSMetalRunLoop;

	public SoundFXData GrabMinigun;

	public SoundFXData VtolExtLoop;

	public SoundFXData VtolJetSteadyLoop;

	public SoundFXData PhoneDial;

	public SoundFXData AmbientRain;

	public SoundFXData AmbientFire;

	public static KowloonS05CSEffectsSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowloonS05CSEffectsSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowloonS05CSEffectsSFX>() != null;
		}
	}
}
