public class KowS03InGameHighSFX : SFXBank
{
	public SoundFXData S_GENERIC_DIALOGUE_FALLBACK_03;

	public static KowS03InGameHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowS03InGameHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowS03InGameHighSFX>() != null;
		}
	}
}
