public class KowS03CutsceneSFX : SFXBank
{
	public SoundFXData S_KOW_DIALOGUE_S03_STRING01_A;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING01_B;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING12_A;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING12_B;

	public SoundFXData S_GENERIC_DIALOGUE_MOVEFORWARD_HINT_02;

	public SoundFXData S_PICKUP_KOW_DIALOGUE_01;

	public SoundFXData S_PICKUP_KOW_DIALOGUE_02;

	public static KowS03CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowS03CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowS03CutsceneSFX>() != null;
		}
	}
}
