public class KowS02CutsceneSFX : SFXBank
{
	public SoundFXData S_KOW_DIALOGUE_S02_STRING01;

	public SoundFXData S_KOW_DIALOGUE_S02_STRING12;

	public SoundFXData S_KOW_DIALOGUE_S02_STRING13;

	public SoundFXData S_KOW_DIALOGUE_S02_STRING12a;

	public static KowS02CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowS02CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowS02CutsceneSFX>() != null;
		}
	}
}
