public class KowS01CutsceneSFX : SFXBank
{
	public SoundFXData S_KOW_DIALOGUE_S01_STRING09;

	public SoundFXData S_KOW_DIALOGUE_S01_STRING10;

	public SoundFXData S_KOW_DIALOGUE_S01_STRING24;

	public SoundFXData S_KOW_DIALOGUE_S01_STRING25;

	public SoundFXData S_KOW_DIALOGUE_S01_STRING26;

	public SoundFXData S_KOW_DIALOGUE_S01_STRING27;

	public SoundFXData S_PICKUP_KOW_INTRO_TACTICAL_01;

	public static KowS01CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowS01CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowS01CutsceneSFX>() != null;
		}
	}
}
