public class KowS05CutsceneSFX : SFXBank
{
	public SoundFXData S_KOW_DIALOGUE_S05_STRING01;

	public SoundFXData S_KOW_DIALOGUE_S05_STRING02;

	public SoundFXData S_KOW_DIALOGUE_S05_STRING02a;

	public SoundFXData S_KOW_DIALOGUE_S05_STRING02b;

	public SoundFXData S_KOW_DIALOGUE_S05_STRING02c;

	public SoundFXData S_KOW_DIALOGUE_S05_STRING02d;

	public SoundFXData S_PICKUP_KOW_DIALOGUE_S05_STRING_30;

	public SoundFXData S_PICKUP_KOW_DIALOGUE_S05_STRING_31;

	public SoundFXData S_PICKUP_KOW_DIALOGUE_S05_STRING_32;

	public static KowS05CutsceneSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowS05CutsceneSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowS05CutsceneSFX>() != null;
		}
	}
}
