public class KowS03InGameSFX : SFXBank
{
	public SoundFXData S_KOW_DIALOGUE_S03_STRING02;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING03;

	public SoundFXData S_ARC_S01_DIALOGUE_36;

	public SoundFXData S_ARC_S01_DIALOGUE_14;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING15;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING17;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING19;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING20;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING22;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING26;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING28;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING29;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING30;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING31;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING33;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING32;

	public SoundFXData S_KOW_DIALOGUE_S03_STRING34;

	public SoundFXData S_GENERIC_DIALOGUE_FALLBACK_03;

	public SoundFXData Explosion;

	public static KowS03InGameSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<KowS03InGameSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<KowS03InGameSFX>() != null;
		}
	}
}
