public class LoadingSFX : SFXBank
{
	public SoundFXData LoadingLoop;

	public SoundFXData LoadingStart;

	public SoundFXData MissionSectionEnd;

	public static LoadingSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<LoadingSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<LoadingSFX>() != null;
		}
	}
}
