public class MenuSFX : SFXBank
{
	public SoundFXData MenuBoxClose;

	public SoundFXData MenuBoxExpand;

	public SoundFXData SelectBack;

	public SoundFXData SelectConfirm;

	public SoundFXData SelectDeploy;

	public SoundFXData SelectEquip;

	public SoundFXData SelectToggle;

	public SoundFXData SoftSelect;

	public SoundFXData BuyInsufficient;

	public SoundFXData BuyConfirm;

	public SoundFXData ItemUnlock;

	public SoundFXData LevelUp;

	public SoundFXData XPBarFill;

	public SoundFXData ToolTip;

	public SoundFXData Blank;

	public SoundFXData MissionLocked;

	public static MenuSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<MenuSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<MenuSFX>() != null;
		}
	}
}
