public class MysteryBoxVOSFX : SFXBank
{
	public SoundFXData S_SURVIVAL_DIALOGUE_MBOPEN_01;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBOPEN_02;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBOPEN_03;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_01;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_02;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_03;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_04;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_05;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_06;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_07;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_08;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_09;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_10;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_11;

	public SoundFXData S_SURVIVAL_DIALOGUE_MBPURCHASE_12;

	public static MysteryBoxVOSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<MysteryBoxVOSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<MysteryBoxVOSFX>() != null;
		}
	}
}
