public class OverHeatWarningSFX : SFXBank
{
	public SoundFXData OverheatWarning;

	public static OverHeatWarningSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<OverHeatWarningSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<OverHeatWarningSFX>() != null;
		}
	}
}
