public class OverwatchSFX : SFXBank
{
	public SoundFXData Hum;

	public SoundFXData RadioVoice;

	public SoundFXData EnterStrategy;

	public SoundFXData ExitStrategy;

	public SoundFXData OverheatWarning;

	public SoundFXData RocketReload;

	public SoundFXData HitMarkerOverwatch;

	public SoundFXData OverheatWarning2D;

	public static OverwatchSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<OverwatchSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<OverwatchSFX>() != null;
		}
	}

	protected override void OnDestroy()
	{
		base.OnDestroy();
	}
}
