public class OverwatchHighSFX : SFXBank
{
	public SoundFXData RadioVoice;

	public static OverwatchHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<OverwatchHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<OverwatchHighSFX>() != null;
		}
	}
}
