public class ParticleSystemSFX : SFXBank
{
	public SoundFXData ElectricSpark;

	public static ParticleSystemSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<ParticleSystemSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<ParticleSystemSFX>() != null;
		}
	}
}
