public class SecurityCameraSFX : SFXBank
{
	public SoundFXData SecurityCamMoveLoop;

	public static SecurityCameraSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<SecurityCameraSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<SecurityCameraSFX>() != null;
		}
	}
}
