public class SetPieceHighSFX : SFXBank
{
	public SoundFXData LowMantleClimbUp;

	public SoundFXData LowMantleLand;

	public SoundFXData HackMineLoop;

	public static SetPieceHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<SetPieceHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<SetPieceHighSFX>() != null;
		}
	}
}
