public class SetPieceSFX : SFXBank
{
	public SoundFXData BinOpen;

	public SoundFXData BinEnter;

	public SoundFXData BinLid;

	public SoundFXData BinExit;

	public SoundFXData HideBodyBin;

	public SoundFXData LockerOpen;

	public SoundFXData LockerEnter;

	public SoundFXData LockerClose;

	public SoundFXData LockerExit;

	public SoundFXData HideBodyLocker;

	public SoundFXData RemoveBodyLocker;

	public SoundFXData TwoManMantle;

	public SoundFXData LowMantleClimbUp;

	public SoundFXData LowMantleLand;

	public SoundFXData DeadBodyPickup;

	public SoundFXData BlackHawkEngine;

	public SoundFXData RappellRopeSlide;

	public SoundFXData HindEngine;

	public SoundFXData HindDamaged;

	public SoundFXData HindDestroyed;

	public SoundFXData HindIdle;

	public SoundFXData HindIdleOnGround;

	public SoundFXData BoatEngineHigh;

	public SoundFXData HackProgressLoop;

	public SoundFXData HackCompStart;

	public SoundFXData HackCompLoop;

	public SoundFXData HackCompComplete;

	public SoundFXData HackSentryStart;

	public SoundFXData HackSentryComplete;

	public SoundFXData HackMineStart;

	public SoundFXData HackMineComplete;

	public SoundFXData ArcGateSlide;

	public static SetPieceSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<SetPieceSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<SetPieceSFX>() != null;
		}
	}
}
