using UnityEngine;

public class StartGameSettings : SingletonMonoBehaviour
{
	private const string kTimerName = "TimerName";

	private const string kComebackReminderName = "ComebackReminder";

	public static StartGameSettings Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<StartGameSettings>();
		}
	}

	public string VERSION
	{
		get
		{
			return TBFUtils.BundleVersion;
		}
	}

	protected override void AwakeOnce()
	{
		if (SecureStorage.Instance.LogFirstGameDateTime())
		{
			SwrveEventsGameplay.FirstRun();
		}
		SecureStorage.Instance.LogLastPlayedDateTime();
		SecureStorage.Instance.LogGameBoot();
		EtceteraPlatformWrapper.SetBadgeCount(0);
		Object.DontDestroyOnLoad(this);
	}

	public void Schedule3DayReminder()
	{
	}

	public void CancelComebackReminder()
	{
	}

	private void OnApplicationPause(bool paused)
	{
		if (paused)
		{
			Schedule3DayReminder();
		}
		else
		{
			EtceteraPlatformWrapper.SetBadgeCount(0);
		}
	}
}
