public class TankSFX : SFXBank
{
	public SoundFXData TankEngine;

	public SoundFXData TankEngineIdle;

	public static TankSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<TankSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<TankSFX>() != null;
		}
	}
}
