public class VocalFriendlySFX : SFXBank
{
	public SoundFXData PainCry;

	public SoundFXData DeathCry;

	public SoundFXData ClaymoreDropped;

	public SoundFXData GrenadeThrown;

	public SoundFXData ManDown;

	public SoundFXData KillConfirm;

	public SoundFXData GrenadeReaction;

	public SoundFXData OrderReceived;

	public SoundFXData StealthKillConfirm;

	public SoundFXData Reload;

	public SoundFXData SniperDown;

	public SoundFXData SniperSpotted;

	public SoundFXData SquadRevived;

	public SoundFXData EnemyRPG;

	public SoundFXData LostAimedShot;

	public SoundFXData FollowMeAnswered;

	public static VocalFriendlySFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<VocalFriendlySFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<VocalFriendlySFX>() != null;
		}
	}
}
