public class VocalFriendlySpetsnazSFX : SFXBank
{
	public SoundFXData PainCry;

	public SoundFXData DeathCry;

	public SoundFXData ClaymoreDropped;

	public SoundFXData GrenadeThrown;

	public SoundFXData ManDown;

	public SoundFXData KillConfirm;

	public SoundFXData GrenadeReaction;

	public SoundFXData OrderReceived;

	public SoundFXData StealthKillConfirm;

	public SoundFXData HelicopterExit;

	public SoundFXData Injured;

	public SoundFXData Reload;

	public SoundFXData SniperDown;

	public SoundFXData SniperSpotted;

	public SoundFXData SquadRevived;

	public SoundFXData EnemyRPG;

	public SoundFXData LostAimedShot;

	public static VocalFriendlySpetsnazSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<VocalFriendlySpetsnazSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<VocalFriendlySpetsnazSFX>() != null;
		}
	}
}
