public class VocalFriendly2HighSFX : SFXBank
{
	public SoundFXData PainCry;

	public SoundFXData DeathCry;

	public SoundFXData ClaymoreDropped;

	public SoundFXData GrenadeThrown;

	public SoundFXData ManDown;

	public SoundFXData KillConfirm;

	public SoundFXData GrenadeReaction;

	public SoundFXData OrderReceived;

	public SoundFXData Reload;

	public SoundFXData SniperDown;

	public SoundFXData SniperSpotted;

	public SoundFXData SquadRevived;

	public SoundFXData FollowMeAnswered;

	public static VocalFriendly2HighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<VocalFriendly2HighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<VocalFriendly2HighSFX>() != null;
		}
	}
}
