public class VocalFriendlyDuboisHighSFX : SFXBank
{
	public SoundFXData KillConfirm;

	public SoundFXData SniperDown;

	public static VocalFriendlyDuboisHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<VocalFriendlyDuboisHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<VocalFriendlyDuboisHighSFX>() != null;
		}
	}
}
