public class VocalRussianHighSFX : SFXBank
{
	public SoundFXData PainCry;

	public SoundFXData DeathCry;

	public SoundFXData GrenadeReaction;

	public SoundFXData OrderReceived;

	public static VocalRussianHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<VocalRussianHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<VocalRussianHighSFX>() != null;
		}
	}
}
