public class VTOLInGameSFX : SFXBank
{
	public SoundFXData AmbVtolExtLoop;

	public SoundFXData AmbVtolSteadyLoop;

	public SoundFXData AmbVTOLInterior;

	public static VTOLInGameSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<VTOLInGameSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<VTOLInGameSFX>() != null;
		}
	}
}
