public class WeaponSFX : SFXBank
{
	public SoundFXData AK47Fire;

	public SoundFXData AK47Reload;

	public SoundFXData AN94Fire;

	public SoundFXData AN94MagOut;

	public SoundFXData AN94MagIn;

	public SoundFXData AN94ChargeBack;

	public SoundFXData AN94ChargeForward;

	public SoundFXData XM8Fire;

	public SoundFXData XM8MagOut;

	public SoundFXData XM8MagIn;

	public SoundFXData XM8ChargeBack;

	public SoundFXData XM8ChargeForward;

	public SoundFXData Type25Fire;

	public SoundFXData Type25FireBurst;

	public SoundFXData Type25MagOut;

	public SoundFXData Type25MagIn;

	public SoundFXData Type25ChargeBack;

	public SoundFXData Type25ChargeForward;

	public SoundFXData KSGFire;

	public SoundFXData KSGPumpBack;

	public SoundFXData KSGPumpForward;

	public SoundFXData KSGReload;

	public SoundFXData M1216Fire;

	public SoundFXData M1216Rechamber;

	public SoundFXData M1216ReloadOut;

	public SoundFXData M1216ReloadIn;

	public SoundFXData M1216Charge;

	public SoundFXData KS23Fire;

	public SoundFXData KS23PumpBack;

	public SoundFXData KS23PumpForward;

	public SoundFXData KS23Reload;

	public SoundFXData AS50Fire;

	public SoundFXData AS50MagOut;

	public SoundFXData AS50MagIn;

	public SoundFXData AS50ChargeBack;

	public SoundFXData AS50ChargeForward;

	public SoundFXData BallistaSilencedFire;

	public SoundFXData BallistaBoltBack;

	public SoundFXData BallistaBoltForward;

	public SoundFXData BallistaMagOut;

	public SoundFXData BallistaMagIn;

	public SoundFXData SVUASFire;

	public SoundFXData SVUASMagOut;

	public SoundFXData SVUASMagIn;

	public SoundFXData SVUASChargeBack;

	public SoundFXData SVUASChargeForward;

	public SoundFXData HAMRFire;

	public SoundFXData HAMRMagOut;

	public SoundFXData HAMRMagIn;

	public SoundFXData HAMRChargeBack;

	public SoundFXData HAMRChargeForward;

	public SoundFXData LSATFire;

	public SoundFXData LSATMagOut;

	public SoundFXData LSATMagIn;

	public SoundFXData LSATChargeBack;

	public SoundFXData LSATChargeForward;

	public SoundFXData QBBFire;

	public SoundFXData QBBMagOut;

	public SoundFXData QBBMagIn;

	public SoundFXData QBBChargeBack;

	public SoundFXData QBBChargeForward;

	public SoundFXData BerettaBurst;

	public SoundFXData BerettaReloadOut;

	public SoundFXData BerettaReloadIn;

	public SoundFXData BerettaChargeBack;

	public SoundFXData BerettaChargeForward;

	public SoundFXData PDWFire;

	public SoundFXData PDWFireBurst;

	public SoundFXData PDWMagOut;

	public SoundFXData PDWMagIn;

	public SoundFXData PDWChargeBack;

	public SoundFXData PDWChargeForward;

	public SoundFXData SkorpionFire;

	public SoundFXData SkorpionFireBurst;

	public SoundFXData SkorpionMagOut;

	public SoundFXData SkorpionMagIn;

	public SoundFXData SkorpionChargeBack;

	public SoundFXData SkorpionChargeForward;

	public SoundFXData VektorFire;

	public SoundFXData VektorFireBurst;

	public SoundFXData VektorMagOut;

	public SoundFXData VektorMagIn;

	public SoundFXData VektorChargeBack;

	public SoundFXData VektorChargeForward;

	public SoundFXData RPGFire;

	public SoundFXData RPGReload;

	public SoundFXData StealthKillMouthGrab;

	public SoundFXData StealthKillKnifeDraw;

	public SoundFXData StealthKnifeSlitThroat;

	public SoundFXData StealthKnifePullOut;

	public SoundFXData StealthNeckCrack;

	public SoundFXData HindRocketFire;

	public SoundFXData HindRocketTrail;

	public SoundFXData TracerWhizBy;

	public SoundFXData TracerWhizByLarge;

	public SoundFXData MortarWhistle;

	public SoundFXData MiniGunSpinUp;

	public SoundFXData MiniGunSpinUpShort;

	public SoundFXData MiniGunSpinDown;

	public SoundFXData MiniGunSpinLoop;

	public SoundFXData MiniGunFireLoop;

	public SoundFXData SentryStart;

	public SoundFXData SentryLoop;

	public SoundFXData SentryStop;

	public SoundFXData TurretShot;

	public SoundFXData OverwatchRocketFire;

	public SoundFXData OverwatchCannonStart;

	public SoundFXData OverwatchCannonLoop;

	public SoundFXData OverwatchCannonFire;

	public SoundFXData ChopperMinigunStart;

	public SoundFXData PickUpAmmo;

	public SoundFXData HitMarker;

	public SoundFXData MeleeSwing;

	public SoundFXData MeleeHit;

	public SoundFXData HeliMachineGunFireLoop;

	public SoundFXData ShieldBash;

	public static WeaponSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<WeaponSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<WeaponSFX>() != null;
		}
	}

	protected override void OnDestroy()
	{
		base.OnDestroy();
	}
}
