public class WeaponHighSFX : SFXBank
{
	public SoundFXData KSGReload;

	public SoundFXData StealthKillKnifeDraw;

	public SoundFXData StealthNeckCrack;

	public SoundFXData HindRocketFire;

	public SoundFXData TracerWhizBy;

	public SoundFXData TracerWhizByLarge;

	public SoundFXData MortarWhistle;

	public SoundFXData MeleeHit;

	public SoundFXData MeleeSwing;

	public static WeaponHighSFX Instance
	{
		get
		{
			return SingletonMonoBehaviour.GetAutoGeneratedSingletonInstance<WeaponHighSFX>();
		}
	}

	public static bool HasInstance
	{
		get
		{
			return SingletonMonoBehaviour.GetSingletonInstance<WeaponHighSFX>() != null;
		}
	}
}
